-- FlowPub — esquema inicial (idempotente). Córrelo en el SQL Editor de Supabase.
-- RLS default-deny en todas las tablas; políticas explícitas abajo.

create extension if not exists "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────────────
-- profiles (1:1 con auth.users)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  username     text unique not null,
  display_name text not null default '',
  bio          text,
  avatar_url   text,
  location     text,
  role         text not null default 'user' check (role in ('user','admin')),
  lang         text not null default 'auto',
  theme        text not null default 'system',
  onboarded    boolean not null default false,
  created_at   timestamptz not null default now()
);

-- Crea el perfil al registrarse.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, username, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'user_name',
             split_part(coalesce(new.email,'voz'), '@', 1)) || '_' || left(new.id::text, 4),
    coalesce(new.raw_user_meta_data->>'full_name',
             new.raw_user_meta_data->>'name',
             split_part(coalesce(new.email,'Voz'), '@', 1)),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Helper: ¿el usuario actual es admin? (Va tras `profiles`: una función SQL valida
-- sus tablas al crearse, así que profiles debe existir primero.)
create or replace function public.is_admin()
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- tags (las 12 categorías; fuente de verdad del onboarding/filtros)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.tags (
  id      bigint generated by default as identity primary key,
  slug    text unique not null,
  name_es text not null,
  name_en text not null,
  active  boolean not null default true,
  sort    int not null default 0
);

insert into public.tags (slug, name_es, name_en, sort) values
  ('arte','Arte','Art',1),
  ('ciencia','Ciencia','Science',2),
  ('libros','Libros','Books',3),
  ('cultura','Cultura','Culture',4),
  ('tecnologia','Tecnología','Technology',5),
  ('viajes','Viajes','Travel',6),
  ('cine','Cine','Film',7),
  ('naturaleza','Naturaleza','Nature',8),
  ('cocina','Cocina','Cooking',9),
  ('deportes','Deportes','Sports',10),
  ('musica','Música','Music',11),
  ('historia','Historia','History',12)
on conflict (slug) do nothing;

-- ─────────────────────────────────────────────────────────────────────────────
-- flows
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.flows (
  id             uuid primary key default gen_random_uuid(),
  author_id      uuid not null references public.profiles(id) on delete cascade,
  title          text not null default '',
  body_md        text not null default '',
  transcript_raw text,
  audio_url      text,
  duration_s     int not null default 0,
  cover_kind     text not null default 'collage'
                   check (cover_kind in ('escher','turrell','flavin','collage')),
  cover_svg      text,
  cover_url      text,
  lang           text not null default 'es',
  status         text not null default 'draft'
                   check (status in ('draft','published','hidden','reported','featured')),
  like_count     int not null default 0,
  comment_count  int not null default 0,
  created_at     timestamptz not null default now()
);
create index if not exists flows_published_idx on public.flows (created_at desc)
  where status in ('published','featured');
create index if not exists flows_author_idx on public.flows (author_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- flow_tags (máx 3 por Flow)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.flow_tags (
  flow_id uuid not null references public.flows(id) on delete cascade,
  tag_id  bigint not null references public.tags(id) on delete cascade,
  primary key (flow_id, tag_id)
);

create or replace function public.enforce_max_tags()
returns trigger language plpgsql as $$
begin
  if (select count(*) from public.flow_tags where flow_id = new.flow_id) >= 3 then
    raise exception 'Un Flow no puede tener más de 3 temas';
  end if;
  return new;
end; $$;
drop trigger if exists trg_max_tags on public.flow_tags;
create trigger trg_max_tags before insert on public.flow_tags
  for each row execute function public.enforce_max_tags();

-- ─────────────────────────────────────────────────────────────────────────────
-- profile_tags (intereses del usuario elegidos en el onboarding; editables luego)
-- La UI pide 3 al arrancar; no ponemos tope duro en BD para poder crecer después.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.profile_tags (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  tag_id     bigint not null references public.tags(id) on delete cascade,
  primary key (profile_id, tag_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- comments (texto | voz)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.comments (
  id             uuid primary key default gen_random_uuid(),
  flow_id        uuid not null references public.flows(id) on delete cascade,
  author_id      uuid not null references public.profiles(id) on delete cascade,
  kind           text not null default 'text' check (kind in ('text','voice')),
  body_text      text,
  audio_url      text,
  transcript_raw text,
  duration_s     int not null default 0,
  like_count     int not null default 0,
  parent_id      uuid references public.comments(id) on delete cascade,
  created_at     timestamptz not null default now()
);
create index if not exists comments_flow_idx on public.comments (flow_id, created_at desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- likes (a flow o a comentario)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.likes (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  flow_id    uuid references public.flows(id) on delete cascade,
  comment_id uuid references public.comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  check (num_nonnulls(flow_id, comment_id) = 1)
);
create unique index if not exists likes_user_flow on public.likes (user_id, flow_id) where flow_id is not null;
create unique index if not exists likes_user_comment on public.likes (user_id, comment_id) where comment_id is not null;

-- Mantiene contadores.
create or replace function public.bump_counts()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_table_name = 'likes' then
    if tg_op = 'INSERT' then
      if new.flow_id is not null then update public.flows set like_count = like_count + 1 where id = new.flow_id; end if;
      if new.comment_id is not null then update public.comments set like_count = like_count + 1 where id = new.comment_id; end if;
    elsif tg_op = 'DELETE' then
      if old.flow_id is not null then update public.flows set like_count = greatest(0, like_count - 1) where id = old.flow_id; end if;
      if old.comment_id is not null then update public.comments set like_count = greatest(0, like_count - 1) where id = old.comment_id; end if;
    end if;
  elsif tg_table_name = 'comments' then
    if tg_op = 'INSERT' then update public.flows set comment_count = comment_count + 1 where id = new.flow_id;
    elsif tg_op = 'DELETE' then update public.flows set comment_count = greatest(0, comment_count - 1) where id = old.flow_id; end if;
  end if;
  return null;
end; $$;

drop trigger if exists trg_like_counts on public.likes;
create trigger trg_like_counts after insert or delete on public.likes
  for each row execute function public.bump_counts();
drop trigger if exists trg_comment_counts on public.comments;
create trigger trg_comment_counts after insert or delete on public.comments
  for each row execute function public.bump_counts();

-- ─────────────────────────────────────────────────────────────────────────────
-- saves (guardados: el «bookmark» del lector)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.saves (
  user_id    uuid not null references public.profiles(id) on delete cascade,
  flow_id    uuid not null references public.flows(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, flow_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- follows (seguir mutuo)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followee_id uuid not null references public.profiles(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (follower_id, followee_id),
  check (follower_id <> followee_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- mensajería
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.conversations (
  id         uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now()
);
create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id         uuid not null references public.profiles(id) on delete cascade,
  primary key (conversation_id, user_id)
);
create table if not exists public.messages (
  id              uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id       uuid not null references public.profiles(id) on delete cascade,
  kind            text not null default 'text' check (kind in ('text','voice')),
  body_text       text,
  audio_url       text,
  transcript_raw  text,
  created_at      timestamptz not null default now()
);
create index if not exists messages_conv_idx on public.messages (conversation_id, created_at);

create or replace function public.is_member(conv uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.conversation_members
    where conversation_id = conv and user_id = auth.uid()
  );
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- notifications
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  actor_id   uuid references public.profiles(id) on delete cascade,
  type       text not null check (type in ('like','follow','comment','voice','mention','flow')),
  flow_id    uuid references public.flows(id) on delete cascade,
  comment_id uuid references public.comments(id) on delete cascade,
  read       boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_idx on public.notifications (user_id, created_at desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- settings (config del admin)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.settings (
  key   text primary key,
  value jsonb not null
);
insert into public.settings (key, value) values
  ('limits',   '{"maxDurationSec":180,"maxTags":3}'::jsonb),
  ('features', '{"openRegistration":true,"generativeUI":false}'::jsonb),
  ('defaults', '{"lang":"auto","theme":"system"}'::jsonb)
on conflict (key) do nothing;

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.profiles enable row level security;
alter table public.tags enable row level security;
alter table public.flows enable row level security;
alter table public.flow_tags enable row level security;
alter table public.profile_tags enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;
alter table public.saves enable row level security;
alter table public.follows enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.settings enable row level security;

-- profiles
drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select using (true);
drop policy if exists profiles_upsert on public.profiles;
create policy profiles_upsert on public.profiles for insert with check (id = auth.uid());
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update using (id = auth.uid());

-- tags
drop policy if exists tags_read on public.tags;
create policy tags_read on public.tags for select using (active or public.is_admin());
drop policy if exists tags_admin on public.tags;
create policy tags_admin on public.tags for all using (public.is_admin()) with check (public.is_admin());

-- flows
drop policy if exists flows_read on public.flows;
create policy flows_read on public.flows for select
  using (status in ('published','featured') or author_id = auth.uid() or public.is_admin());
drop policy if exists flows_insert on public.flows;
create policy flows_insert on public.flows for insert with check (author_id = auth.uid());
drop policy if exists flows_update on public.flows;
create policy flows_update on public.flows for update
  using (author_id = auth.uid() or public.is_admin());
drop policy if exists flows_delete on public.flows;
create policy flows_delete on public.flows for delete
  using (author_id = auth.uid() or public.is_admin());

-- flow_tags
drop policy if exists flow_tags_read on public.flow_tags;
create policy flow_tags_read on public.flow_tags for select using (true);
drop policy if exists flow_tags_write on public.flow_tags;
create policy flow_tags_write on public.flow_tags for all
  using (exists (select 1 from public.flows f where f.id = flow_id and f.author_id = auth.uid()))
  with check (exists (select 1 from public.flows f where f.id = flow_id and f.author_id = auth.uid()));

-- profile_tags (lectura pública; cada quien escribe los suyos)
drop policy if exists profile_tags_read on public.profile_tags;
create policy profile_tags_read on public.profile_tags for select using (true);
drop policy if exists profile_tags_write on public.profile_tags;
create policy profile_tags_write on public.profile_tags for all
  using (profile_id = auth.uid()) with check (profile_id = auth.uid());

-- comments
drop policy if exists comments_read on public.comments;
create policy comments_read on public.comments for select
  using (exists (
    select 1 from public.flows f where f.id = flow_id
    and (f.status in ('published','featured') or f.author_id = auth.uid() or public.is_admin())
  ));
drop policy if exists comments_insert on public.comments;
create policy comments_insert on public.comments for insert with check (author_id = auth.uid());
drop policy if exists comments_update on public.comments;
create policy comments_update on public.comments for update
  using (author_id = auth.uid() or public.is_admin());
drop policy if exists comments_delete on public.comments;
create policy comments_delete on public.comments for delete
  using (author_id = auth.uid() or public.is_admin());

-- likes
drop policy if exists likes_read on public.likes;
create policy likes_read on public.likes for select using (true);
drop policy if exists likes_insert on public.likes;
create policy likes_insert on public.likes for insert with check (user_id = auth.uid());
drop policy if exists likes_delete on public.likes;
create policy likes_delete on public.likes for delete using (user_id = auth.uid());

-- saves (privados: cada quien ve y maneja solo los suyos)
drop policy if exists saves_own on public.saves;
create policy saves_own on public.saves for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- follows
drop policy if exists follows_read on public.follows;
create policy follows_read on public.follows for select using (true);
drop policy if exists follows_insert on public.follows;
create policy follows_insert on public.follows for insert with check (follower_id = auth.uid());
drop policy if exists follows_delete on public.follows;
create policy follows_delete on public.follows for delete using (follower_id = auth.uid());

-- conversations / members / messages (solo integrantes)
drop policy if exists conv_read on public.conversations;
create policy conv_read on public.conversations for select using (public.is_member(id));
drop policy if exists conv_insert on public.conversations;
create policy conv_insert on public.conversations for insert with check (auth.uid() is not null);

drop policy if exists members_read on public.conversation_members;
create policy members_read on public.conversation_members for select using (public.is_member(conversation_id));
-- Solo un integrante invita; la única alta "propia" permitida es la del
-- creador sobre una conversación aún vacía (bootstrap). Sin esto, cualquiera
-- podría auto-agregarse a conversaciones ajenas y leer sus mensajes.
drop policy if exists members_insert on public.conversation_members;
create policy members_insert on public.conversation_members for insert
  with check (
    public.is_member(conversation_id)
    or (
      user_id = auth.uid()
      and not exists (
        select 1 from public.conversation_members m
        where m.conversation_id = conversation_members.conversation_id
      )
    )
  );

drop policy if exists messages_read on public.messages;
create policy messages_read on public.messages for select using (public.is_member(conversation_id));
drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert
  with check (sender_id = auth.uid() and public.is_member(conversation_id));

-- notifications (solo el destinatario; el alta la hacen triggers/servicio)
drop policy if exists notifications_read on public.notifications;
create policy notifications_read on public.notifications for select using (user_id = auth.uid());
drop policy if exists notifications_update on public.notifications;
create policy notifications_update on public.notifications for update using (user_id = auth.uid());

-- settings (lectura pública para límites/defaults; escritura solo admin)
drop policy if exists settings_read on public.settings;
create policy settings_read on public.settings for select using (true);
drop policy if exists settings_admin on public.settings;
create policy settings_admin on public.settings for all using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────────────────────────────────────────
-- Privilegios de columna (defensa además de RLS): nadie se auto-promueve a
-- admin ni infla contadores por la API; esas columnas las mueven solo los
-- triggers/el servidor (service_role). El update queda acotado por columnas.
-- ─────────────────────────────────────────────────────────────────────────────
revoke update on public.profiles from anon, authenticated;
grant update (username, display_name, bio, avatar_url, location, lang, theme, onboarded)
  on public.profiles to authenticated;

revoke update on public.flows from anon, authenticated;
grant update (title, body_md, transcript_raw, audio_url, duration_s,
              cover_kind, cover_svg, cover_url, lang, status)
  on public.flows to authenticated;

revoke update on public.comments from anon, authenticated;
grant update (body_text) on public.comments to authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- Storage: buckets audio / avatars / covers (carpeta por usuario: <uid>/...)
-- ─────────────────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public) values
  ('audio','audio', true),
  ('avatars','avatars', true),
  ('covers','covers', true)
on conflict (id) do nothing;

drop policy if exists storage_read on storage.objects;
create policy storage_read on storage.objects for select
  using (bucket_id in ('audio','avatars','covers'));
drop policy if exists storage_upload_own on storage.objects;
create policy storage_upload_own on storage.objects for insert
  with check (bucket_id in ('audio','avatars','covers')
              and auth.uid()::text = (storage.foldername(name))[1]);
drop policy if exists storage_update_own on storage.objects;
create policy storage_update_own on storage.objects for update
  using (auth.uid()::text = (storage.foldername(name))[1]);
drop policy if exists storage_delete_own on storage.objects;
create policy storage_delete_own on storage.objects for delete
  using (auth.uid()::text = (storage.foldername(name))[1]);
